# Generated by Django 5.1.6 on 2025-02-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='FileNotes',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='Add',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
