# Generated by Django 5.1.6 on 2025-02-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_filenotes_alter_students_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='students',
            name='creationTime',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profilePic',
        ),
    ]
